"""GENERATED by scripts/sync-config.mjs from shared/config.json — do not edit."""

SERVICE_NAMES = (
    "api-gateway",
    "order-service",
    "payment-service",
    "inventory-service",
)

SERVICE_LATENCY: dict[str, dict[str, float]] = {
    "api-gateway": {"min": 5, "max": 15},
    "order-service": {"min": 10, "max": 30},
    "payment-service": {"min": 40, "max": 120},
    "inventory-service": {"min": 15, "max": 40},
}

FAILURE_PARAMS: dict[str, dict[str, float]] = {
    "latency_spike": {
        "extra_latency_min": 800,
        "extra_latency_max": 1500,
        "error_rate": 0,
    },
    "error_burst": {
        "extra_latency_min": 0,
        "extra_latency_max": 0,
        "error_rate": 0.4,
    },
    "cascading_timeout": {
        "extra_latency_min": 2000,
        "extra_latency_max": 3000,
        "error_rate": 0.5,
    },
}

FAILURE_MODES = tuple(FAILURE_PARAMS.keys())

INCIDENT_KV_KEY = "current_incident"
INCIDENT_DURATION_MS = 300000
INCIDENT_SPAWN_PROBABILITY = 0.2

SYNTHETIC_CHECKOUT_MIN = 3
SYNTHETIC_CHECKOUT_MAX = 7

ANALYTICS_COLUMNS = {
    "service": "blob4",
    "status": "blob6",
    "error_message": "blob7",
    "duration_ms": "double1",
}
