// GENERATED by scripts/sync-config.mjs from shared/config.json — do not edit.

export const SERVICE_NAMES = [
  "api-gateway",
  "order-service",
  "payment-service",
  "inventory-service"
] as const;

export const ANALYTICS_DATASET = "tracehound_analytics";
export const DEFAULT_QUERY_WINDOW_MINUTES = 15;

export const ANALYTICS_COLUMNS = {
  service: "blob4",
  status: "blob6",
  errorMessage: "blob7",
  durationMs: "double1",
} as const;

export const FAILURE_MODES = [
  "latency_spike",
  "error_burst",
  "cascading_timeout"
] as const;
export const INCIDENT_DURATION_MS = 300000;

export const CLAUDE_MODEL = "claude-sonnet-4-6";
export const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
export const ANTHROPIC_VERSION = "2023-06-01";
export const AGENT_MAX_ITERATIONS = 5;
export const AGENT_MAX_TOKENS = 2048;
export const INVESTIGATE_DEADLINE_MS = 22000;
