#!/usr/bin/env node
/**
 * Reads shared/config.json and writes generated config into agent + simulation.
 * Run: npm run sync-config
 * CI:  npm run sync-config:check  (exit 1 if generated files would change)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const checkOnly = process.argv.includes('--check');
const cfg = JSON.parse(readFileSync(join(root, 'shared/config.json'), 'utf8'));

const header =
  '// GENERATED by scripts/sync-config.mjs from shared/config.json — do not edit.\n';

const ts = `${header}
export const SERVICE_NAMES = ${JSON.stringify(cfg.serviceNames, null, 2)} as const;

export const ANALYTICS_DATASET = ${JSON.stringify(cfg.analyticsDataset)};
export const DEFAULT_QUERY_WINDOW_MINUTES = ${cfg.agent.defaultQueryWindowMinutes};

export const ANALYTICS_COLUMNS = {
  service: ${JSON.stringify(cfg.analyticsColumns.service)},
  status: ${JSON.stringify(cfg.analyticsColumns.status)},
  errorMessage: ${JSON.stringify(cfg.analyticsColumns.errorMessage)},
  durationMs: ${JSON.stringify(cfg.analyticsColumns.durationMs)},
} as const;

export const FAILURE_MODES = ${JSON.stringify(Object.keys(cfg.failureParams), null, 2)} as const;
export const INCIDENT_DURATION_MS = ${cfg.incident.durationMs};

export const CLAUDE_MODEL = ${JSON.stringify(cfg.agent.claudeModel)};
export const ANTHROPIC_API_URL = ${JSON.stringify(cfg.agent.anthropicApiUrl)};
export const ANTHROPIC_VERSION = ${JSON.stringify(cfg.agent.anthropicVersion)};
export const AGENT_MAX_ITERATIONS = ${cfg.agent.maxIterations};
export const AGENT_MAX_TOKENS = ${cfg.agent.maxTokens};
export const INVESTIGATE_DEADLINE_MS = ${cfg.agent.investigateDeadlineMs};
`;

const pyHeader =
  '"""GENERATED by scripts/sync-config.mjs from shared/config.json — do not edit."""\n\n';

const latencyLines = Object.entries(cfg.serviceLatency)
  .map(
    ([name, v]) =>
      `    ${JSON.stringify(name)}: {"min": ${v.min}, "max": ${v.max}},`
  )
  .join('\n');

// JSON camelCase (extraLatencyMin) → Python snake_case (extra_latency_min).
const failureLines = Object.entries(cfg.failureParams)
  .map(
    ([mode, v]) =>
      `    ${JSON.stringify(mode)}: {\n` +
      `        "extra_latency_min": ${v.extraLatencyMin},\n` +
      `        "extra_latency_max": ${v.extraLatencyMax},\n` +
      `        "error_rate": ${v.errorRate},\n` +
      `    },`
  )
  .join('\n');

const serviceTuple = cfg.serviceNames.map((n) => `    ${JSON.stringify(n)},`).join('\n');

const py = `${pyHeader}SERVICE_NAMES = (
${serviceTuple}
)

SERVICE_LATENCY: dict[str, dict[str, float]] = {
${latencyLines}
}

FAILURE_PARAMS: dict[str, dict[str, float]] = {
${failureLines}
}

FAILURE_MODES = tuple(FAILURE_PARAMS.keys())

INCIDENT_KV_KEY = ${JSON.stringify(cfg.incident.kvKey)}
INCIDENT_DURATION_MS = ${cfg.incident.durationMs}
INCIDENT_SPAWN_PROBABILITY = ${cfg.incident.spawnProbability}

SYNTHETIC_CHECKOUT_MIN = ${cfg.syntheticCheckout.min}
SYNTHETIC_CHECKOUT_MAX = ${cfg.syntheticCheckout.max}

ANALYTICS_COLUMNS = {
    "service": ${JSON.stringify(cfg.analyticsColumns.service)},
    "status": ${JSON.stringify(cfg.analyticsColumns.status)},
    "error_message": ${JSON.stringify(cfg.analyticsColumns.errorMessage)},
    "duration_ms": ${JSON.stringify(cfg.analyticsColumns.durationMs)},
}
`;

const tsPath = join(root, 'agent/src/config/index.ts');
const pyPath = join(root, 'simulation/src/config/__init__.py');

if (checkOnly) {
  const tsOnDisk = readFileSync(tsPath, 'utf8');
  const pyOnDisk = readFileSync(pyPath, 'utf8');
  let ok = true;
  if (tsOnDisk !== ts) {
    console.error('Drift: agent/src/config/index.ts is out of sync with shared/config.json');
    ok = false;
  }
  if (pyOnDisk !== py) {
    console.error('Drift: simulation/src/config/__init__.py is out of sync with shared/config.json');
    ok = false;
  }
  if (!ok) {
    console.error('Run: npm run sync-config');
    process.exit(1);
  }
  console.log('Config sync OK');
  process.exit(0);
}

writeFileSync(tsPath, ts);
writeFileSync(pyPath, py);
console.log('Synced shared/config.json → agent/src/config + simulation/src/config');
